### PR TITLE
Change patchouli to be an all-modes config

### PR DESCRIPTION
**Pull request by Rodg88**
Disables advancement locks on all modes.

### CODE REVIEW

**Comment by Rodg88** [comment]
I hope this is the correct way to change from using config swapper to not using it for a general config file

**Comment by NillerMedDild** [comment]
It is correct gj 👍 
However, you also need to force delete the old files through the serverconfigupdater config, as launchers don't typically remove files during modpack updates.

**Comment by Rodg88** [comment]
gotacha, done.

**Comment by NillerMedDild** [comment]
Thank you kindly 😀

**Pull request merged**
