### PR TITLE
[Expert] Fixes surrounding early Ars Nouveau and Eidolon

### LINKED ISSUE #4260: [expert] New Un-Crucible recipes lock ars nouveau with present arcane gold recipe, and a suggested solution.
### Modpack Version

02/17/22 development branch, 0.5.25 release

### Describe your issue.

With the new arcane gold recipe, it requires source to create. The sourcelinks are locked behind gold inlays, which are made with arcane gold. 
Short of doing a LOT of looting and getting lucky, ars nouveau is locked out at present. I suggest making that recipe use **Pewter** inlays for at least the agronomic, which are obtainable. 

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

Yes

### User Modifications

metalbarrels-3.3a.jar
hexblades-1.16.5-0.0.9.3.jar
Babel-1.0.5.jar
bagofyurting-1.16.4-1.2.0.1.jar
interactive_corporea-1.2.jar
forbidden_arcanus-16.2.2.jar
EvilCraft-1.16.5-1.1.12.jar
eidolonrecipes-1.16.5-1.0.jar
configswapper-2.5.jar
turtlemancy-1.16.5-1.6.3.jar
tomeofblood-1.16.5-1.2.3.jar
smarterfarmers-1.16.5-1.2.1.jar
nolakes-0.1-1.16.4.jar.disabled
MythicBotany-1.16.5-1.4.19.jar
NaturesAura-34.3.jar
geckolib-forge-1.16.5-3.0.65.jar
MushroomQuest_1.16.5_v3.2.jar
ars_nouveau-1.16.5-1.24.16.jar
jei-professions-1.0.0-1.16.4.jar
DeLogger-3.0.4-build.20+mc1.16.5.jar
Druidcraft-1.16.5-0.4.54.jar
Modest+Roses+1.2.3+-+Forge+1.16.5.jar
autumnity-1.16.5-2.1.2.jar
betteranimals-1.16.4-5.5.0.jar
cherishedworlds-forge-1.16.5-5.1.1.0.jar
seasonals-1.16.5-2.0.0.jar
neapolitan-1.16.5-2.1.0.jar
Lollipop-1.16.5-3.2.9.jar
LostTrinkets-1.16.5-0.1.27.jar
serverconfigupdater-1.3.jar
TravelersTitles-1.16.4-1.5.jar
abyg-1.2-forge.jar
Paxi-Forge-1.16.4-1.0.jar
Buddycards-1.16.5-2.5.2.jar
BetterDungeons-1.16.4-1.2.1.jar
creeperconfetti-3.7.jar
ExplorersCompass-1.16.5-1.1.2-forge.jar
Notes-1.16.5-1.2.3.jar
NekosEnchantedBooks-1.16-1.4.0.jar
playerex-1.1.8-1.16.5.jar
relicex-1.0.0-1.16.4.jar
NaturesStarlight-1.1.22.jar
EnigmaticLegacy-2.11.11.jar
ArcaneFundamentals-alpha-9.jar
SpawnerFix-1.16.2-1.0.0.2.jar
no-nitwits-1.16.4-1.0.0.jar
weirdinggadget-1.16.(2-4)-2.2.7.jar
betteranimalsplus-1.16.5-11.0.0-forge.jar.disabled
whisperwoods-1.16.5-2.0.2.jar.disabled
endrem_forge-5.0.1-R-1.16.5.jar
mana-and-artifice-1.5.1.6.jar
ExtraBotany-r1.2-68.jar
BetterStrongholds-1.16.4-1.2.1.jar
upstream-1.0.jar
MmmMmmMmmMmm-1.16.5-1.3.1.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
blue_skies-1.16.5-1.1.3.jar
campfiretorches-1.16.3-1.0.3.jar
farmersdelightintegrations-1.16.5-1.2.jar
farmerstea-1.16.5-1.3.jar
simplytea-1.16.5-2.4.0.jar
tea_kettle-1.16.5-0.4.0.0.jar
beenfo-1.16.4-forge35.0.7-1.2.jar
wandering_trapper-1.16.5-0.1.2.jar
PackingTape-1.16.5-0.10.1.jar

### Did the issue happen in singleplayer or on a server?

Singleplayer

### PR DESCRIPTION
**Pull request by MuteTiefling**
Arcane gold change:

image
Spend source, or spend a conduit. This allows getting to source links to actually be able to make source again. Resolves #4260

New Spell Turret recipe
image

Enchanted Spell Turret
image

Crystallizer
image

Brazier
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Seashells now have a chance to drop nautilus shells, prismarine shards, and prismarine crystals when broken. Removed the shapeless recipe of shells > prismarine shard.

Left click breaks, right click picks them up as usual.

**Comment by MuteTiefling** [comment]
Fix broken candle recipes

**Comment by ZephyrWindSpirit** [comment]
In the case of the new recipe, because the inlays take 4 arcane gold each, could the recipe give 4 arcane gold, to save on resources? Otherwise you're costing 4 conduits without source to get a sourcelink.

**Comment by MuteTiefling** [comment]
New seal gift loot. Overrides the default loot entirely. 256 drops looks like this:
image

Between this and the fact that PVJ shells now give nautilus sometimes when broken, conduits should be considerably easier to obtain early game without having to hunt mobs. They also show up very frequently in underwater loot as a result of previous changes. Therefore, I think it's fine that you have to do the expensive conduit recipe a few times to get your first sourcelink.

**Comment by MuteTiefling** [comment]
Quests updated to point people towards the various options for nautilus shells
image

**Comment by MuteTiefling** [comment]
Should resolve #4262 as well now.

**Comment by ZephyrWindSpirit** [comment]
I had to wiki what was meant by seal gifts. If they take any fish, including aquaculture, that should work fine.

**Comment by ZephyrWindSpirit** [comment]
One more suggestion; serrated shark teeth in the loot pool for seals. They are the deep water sharks.

**Comment by MuteTiefling** [comment]
Quick update to the Offering Table too:
image

**Comment by MuteTiefling** [comment]
> One more suggestion; serrated shark teeth in the loot pool for seals. They are the deep water sharks.

I'd rather leave those to Alex's default method of obtaining them, from Frilled Sharks. You don't need them for much, so there's no need to clutter up this loot table with more things.

**Comment by ZephyrWindSpirit** [comment]
> I'd rather leave those to Alex's default method of obtaining them, from Frilled Sharks. You don't need them for much, so there's no need to clutter up this loot table with more things.
Thats more then fair. Looking good.

**Review by NillerMedDild — APPROVED** [review]
Excellent work as always, I feel like we're in the home stretch :D

**Comment by MuteTiefling** [comment]
> Excellent work as always, I feel like we're in the home stretch :D

Yep!

**Pull request merged**
