### PR TITLE
Make the brass bee output brass dust from emendatus instead of crushed brass from create

### PR DESCRIPTION
**Pull request by Gcat101**
Title.

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Why?

**Comment by Gcat101** [comment]
because every other alloy bee outputs dusts from emendatus?

**Comment by MuteTiefling** [comment]
@TemperedFool can correct me if I'm wrong, but I seem to recall that we did this intentionally to keep the processing of the bee outputs somewhat related to Create processing, since brass is from Create.

**Comment by TemperedFool** [comment]
Yeah, when possible we stuck with products that required more processing. Tbh, dusts are too easy.

**Comment by Gcat101** [comment]
Ah ok. Just seemed weird that it's the only bee that's like that.

**Comment by NielsPilgaard** [comment]
Thanks but no thanks :P

**Pull request closed without merging**
