### PR TITLE
[Expert] Automated Iridescent Altar

### PR DESCRIPTION
**Pull request by MuteTiefling**
First of hopefully several masterful machinery machines to assist with endgame. 

Observatory Lens
image

Other lenses all translated too. Same inputs, just run through the machine. 
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Also includes Building Gadget pattern as the in game display is... not great.

**Comment by MuteTiefling** [comment]
still need recipes for the control blocks too

**Comment by MuteTiefling** [comment]
image

**Comment by MuteTiefling** [comment]
Item Input
image

Item Output
image

Fluid Input
image

FE Input
image

Controller
image

**Comment by MuteTiefling** [comment]
All set on this one.

**Review by NillerMedDild — APPROVED** [review]
Nice work!

**Pull request merged**
