### PR TITLE
[Expert] Modular Routers recipe pass and general cleanup

### PR DESCRIPTION
**Pull request by MuteTiefling**
Sender, Puller, and Fluid MK1 modules
image

Also in ARC Furnace
image

Speed Upgrade
image

Buffed PNC's speed upgrade craft as well
image

Energy Output Modules:
image

Stack upgrades:
image

Sender MK3
image

Fluid Transfer Upgrade
image

Flinger
image

Insightful Crystal
image

XP Vacuum Augment
image

Vacuum Module
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Update charging runes to use lime or green runes
image

**Comment by MuteTiefling** [comment]
Moves the tinker's planner icon to a more visible default location:
image

**Comment by MuteTiefling** [comment]
Unify Redstone
image

Resolves: #4070

**Comment by MuteTiefling** [comment]
Add Shield tags to resolve #3964 and #3904

**Comment by MuteTiefling** [comment]
Got a bit carried away there :D

**Review by NillerMedDild — APPROVED** [review]

**Pull request merged**
