### PR TITLE
[Expert] Recipe tweaks

### PR DESCRIPTION
**Pull request by MuteTiefling**
Integrated Dynamics

Reduce cost of Crafting Interfaces
image

Make Logic Programmer slightly easier
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Add note to PNC's quests about compatibility with Mek and IE

image

Resolves: #4623

**Comment by MuteTiefling** [comment]
Update Building Gadget pattern for Automated Engineer's Workbench

**Comment by MuteTiefling** [comment]
Reduce LP Cost of Runes of Capacity by using a lower tier slate. 

image

**Review by NillerMedDild — APPROVED** [review]
Great changes!

**Pull request merged**
