### PR TITLE
Allow more items to stack to 64

### PR DESCRIPTION
**Pull request by MuteTiefling**
Mostly QoL. These ones shouldn't break anything.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Do the IF upgrades not depend on NBT?

**Comment by MuteTiefling** [comment]
They have NBT on the, yes. But it's all the same for a given tier of upgrade. They already stack to 16 as is, this just brings it up.

**Comment by NillerMedDild** [comment]
Alright 👍

**Comment by Discomanco** [comment]
Could put in requests for more items, like empty Buckets and Honey Bottles

**Comment by MuteTiefling** [comment]
honey bottles seem kinda powerful, given their potion effects/high saturation.

**Comment by TemperedFool** [comment]
Maybe just vanilla honey bottles?

**Comment by theboo** [comment]
Oreos stack to 64 and they kinda destroy any honey lol

**Comment by MuteTiefling** [comment]
That's fair. Still harder to get than most honey. But I think we can do honey too

**Comment by Discomanco** [comment]
Signs of all kinds
Eggs of probably multiple kinds

**Pull request merged**
