### PR TITLE
[Expert] Bragging Rights

### PR DESCRIPTION
**Pull request by MuteTiefling**
MM machine is only a standin for now so these can be playtested. Work is in progress on a real structure.

Botanical Mastery: 50x needed
image

Astronomy Mastery: 50x needed
image

Alchemy Mastery: 50x needed
image

Ritual Mastery: 10x needed. I think they can share some blood altars :P
image

Aura Mastery: 50x needed
image

Engineering Mastery: 50x needed. Requires sending materials for an arc furnace, distillation tower, and pumpjack for each
image

Energistics Mastery: 1x needed. Let them share some power
image

Dimensional Mastery: 50x needed
image

Battle Mastery: 10x needed to make a defense force for all 
image

Excavation Mastery: 50x needed
image

Culinary Mastery: 50x needed
image

Automation Mastery: 50x needed
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
might have to trim a few of these... they're hard to read when they end up 'out of bounds' like in the excavation mastery

**Comment by MuteTiefling** [comment]
Forgot to do the recipes for the machine inputs. Also added mana input requirement to each recipe above.

**Comment by NillerMedDild** [comment]
> might have to trim a few of these... they're hard to read when they end up 'out of bounds' like in the excavation mastery

Time to make intermediate crafting ingredients? 

For example, all of the IE engineering blocks + radiator etc -> Super Heavy Engineering Block? :D

**Comment by MuteTiefling** [comment]
Yeah I was thinking the same. I'll put that together and see how it looks.

**Comment by MuteTiefling** [comment]
Various sets made in the Pressure Chamber:
Distillation +  Meka Pants
image
Arc Furnace + Meka Boots
image
Mining Gadget + Meka Chest
image
Pedestal Quarry + Chalk
image
Meka Helmet + Fluxbore
image
Mekatool + Occultism set
image
Excavator + Pumpjack
image

**Comment by MuteTiefling** [comment]
OK, think this is looking pretty good. next up is a rework of the quest chapter.

Rid is working on art soon, tree structure is in progress,

**Comment by MuteTiefling** [comment]
Reduced the number of mining lasers needed for Excavation

Added in a few nucleosynthesis recipes as an alternative route to Powah Crystals, as these get very expensive here. 
Blazing
image

Niotic
image

Spirited
image

Nitro
image

**Comment by MuteTiefling** [comment]
Re-enabled gathering dragonstone and dreamwood from Alfheim

Add ARC recipe to revert dragonstone to mana diamond
image
image

**Comment by MuteTiefling** [comment]
Add the easier crystal glass recipe to the arc furnace:
image

**Review by NillerMedDild — APPROVED** [review]

**Comment by MuteTiefling** [comment]
Masterful Machiner parts for the tree:
Tweak to Branch of Yggdrasil
image

Item output
image

Item input
image

Fluid Input
image

Mana Input
image

**Comment by MuteTiefling** [comment]
Controller:
image

**Comment by MuteTiefling** [comment]
Rune Holders
image
image

**Comment by MuteTiefling** [comment]
Gonna go ahead and get this merged for now. Art/quests/structure can come later. I'd like the testers to be able to get into it and offer feedback.

**Pull request merged**
