### PR TITLE
[Expert] Endgame Recipe Prep

### PR DESCRIPTION
**Pull request by MuteTiefling**
Getting recipes in place to assist with the automation needs of end game.

Add enchanting focus tomes and golden apple to Arc Furnace. The golden apple has other automation friendly recipes, but this gives the player some choices in how they approach it.
image
image
image
image
image

Some of these have been updated to use different materials. Those changes are reflected in the Alloy Furnace recipes as well. 

Astral Glass Lenses
image

Iridescent Altar
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
New Masterful Machine: Gaia Reactor

**Comment by NillerMedDild** [comment]
Damn that looks cool!

**Comment by MuteTiefling** [comment]
Reactor Controller
image

**Comment by MuteTiefling** [comment]
Automation friendly Elven Spreader
image

Update Gaia Spreader Recipe and make it automation friendly
image
image

Update Mana Collector recipe
image

This _should_ make all planned end game recipes automation ready.

**Comment by MuteTiefling** [comment]
oop, one more:
Fortune upgrade modified to be automation friendly
image

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Awesome work  👌

**Pull request merged**
