### PR TITLE
[Expert] Remove Eidolon Magic Workbench

### PR DESCRIPTION
**Pull request by MuteTiefling**
Seems there's a nasty dupe here that's never going to get fixed. Removing and moving all recipes to new homes. 

Luminous Crafting Table
image

Enchanting Table
image

Stone Altar
image

Soul Enchanter
image

Warded Mail
image

Wicked Weave
image

Mind-Shielding Plate
image

Resolute Belt
image

Gravity Belt
image

Bonechill Wand moved earlier, easy starting weapon
image

Souflire Wand
image

Warlock Armor:
image
image
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
New Masterful Machine, the Wicked Altar.

Scythe
image

**Comment by ZephyrWindSpirit** [comment]
How do we build the wicked altar?

**Comment by MuteTiefling** [comment]
> How do we build the wicked altar?

You do see the part where this is a Draft, right?

**Comment by ZephyrWindSpirit** [comment]
Curiosity. I looked at the commits so far for now.

**Comment by MuteTiefling** [comment]
Patience :D

**Comment by MuteTiefling** [comment]
Wicked Altar Controller
image

Inputs and outputs
image

All recipes require some amount of blood. Not a lot, as this is an entry level MM. Hopefully people will find this relatively inexpensive for this early stage.

**Comment by MuteTiefling** [comment]
Opting to leave this one on the plain side so people can decorate as they please. Inputs/outputs are accessible from behind or below.

**Comment by MuteTiefling** [comment]
Reaping Modifier: 
image

**Comment by NillerMedDild** [comment]
Nice work! 👌

**Pull request merged**
