### PR TITLE
Remove the catnip larva in favor of the kitten larva (#4937)

### PR DESCRIPTION
**Pull request by Quezler**
Removing the catnip_larva should have no side-effects, it crafted into a default bee anyways.

### CODE REVIEW

**Comment by Quezler** [comment]
As mentioned at the bottom of the now merged #5001 the catnip larva is now gone & the kitten larva took its rightful place.

This pull request is still needed in order to undo #4938, as well as preventing a jar recipe for the catnip comb.

**Comment by MuteTiefling** [comment]
image

**Comment by Quezler** [comment]
@MuteTiefling did you pull? this change should have fixed that error, and it doesn't show up as an error in my latest pr for which the ci ran 🤔

**Comment by MuteTiefling** [comment]
I just pulled again and it's fixed ^_~

**Pull request merged**
