### PR TITLE
[Expert] Nature's Aura tweaks to better prepare the player for the threat the Masticator poses

### PR DESCRIPTION
**Pull request by MuteTiefling**
Move the Altar of Birthing recipe to the Ritual of the Forest
image

Cost now includes a large quantity of sunmetal, driving up the aura cost to even make it. 

Cost of Sunstone increased, crafting time reduced, as the altar wasn't able to keep up with a pure daisy making living rock. 

Add recipe for warded stone to the altar, granting a solid material cost reduction at a steep aura cost
image

Add recipe to quadruple mana dust
image

Add recipe to generate floral fertilizer without dye. This cost about half as much aura as you get by using it to make flowers for an Herbivorous Absorber, so it does create a positive aura feedback.

image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Change Golden Nether Bricks for parity with Golden Stone Bricks:
image
Unrelated to the rest of this, but noticed it was out of place :D

**Comment by MuteTiefling** [comment]
Still looking for some other ways to get more aura used early game to promote the need for aura gen prior to making the Altar of Birthing.

**Comment by NielsPilgaard** [comment]
I think this is a great way of nudging players in the right direction!

**Comment by MuteTiefling** [comment]
Got a few more changes coming in here

**Comment by MuteTiefling** [comment]
Adds a list of valid projectiles to JEI for the Shooting Mark. Leaving numbers out of it to respect the mod, but at least you get an idea of what's available.

image

**Comment by MuteTiefling** [comment]
New quest structure in the Expert Section:
image

Begins with a warning on Aura and a quest to make one of the two early powerful aura generators before directing the player to prep for the masticator.
image

**Comment by MuteTiefling** [comment]
Infusion recipes for Slime to Sky Slime and Ichor. These are needed a lot in tech and this provides a simple way to create them.
image
image

Bonus recipes that have an aura and time reduction compared to doing one at a time as above.
image
image

**Comment by MuteTiefling** [comment]
Alternate Polished Rose Quartz:
image

**Comment by TemperedFool** [comment]
> Alternate Polished Rose Quartz:
> 
> image
> 
> 

I will be using this to automate polished quartz I think... no more sandpaper!

**Comment by MuteTiefling** [comment]
Add a very costly (in terms of aura) recipe for Overgrowth Seeds
image

Also updates the Chakram and Flare Chakram recipes.
image
image

**Comment by MuteTiefling** [comment]
Move Marvelous Clay to the Natural Altar
image

And Mythical to Mana Infusion.
image

Gives these clays a bit more of a feel of progression.

**Comment by MuteTiefling** [comment]
Alright. Should be set on this one. Overall, I think this gives the Altar much more purpose, and should drive the players to automating aura well before they meet the masticator, both as a result of the high aura costs in making the altar of birthing, and by way of the extra utility recipes.

**Review by NielsPilgaard — APPROVED** [review]

**Pull request merged**
