### PR TITLE
[Expert] Remove dependency on IE coke oven

### PR DESCRIPTION
**Pull request by MuteTiefling**
It's slow, you use it once, and then you're done forever. No point.

Pyrolizer will take it's place instead: 
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Pyrolyzer recipes made roughly 3x slower. Coal blocks may be processed, however, processing 9 coal in the time that 8 would run as single items.

Should still be plenty fast with upgrades.

image


Tinker's Crystals added to IE Blast Furnace, process in 100 ticks as opposed to 400 in vanilla blast furnace.

image

**Review by NillerMedDild — APPROVED** [review]
I reluctantly approve 😄
Did you update the quests to reflect the change?

**Comment by MuteTiefling** [comment]
I think I got everything, could use a second pair of eyes though.

**Comment by NillerMedDild** [comment]
Alrighty,  I'll merge and have a look before next update 😀

**Comment by NillerMedDild** [comment]
I added an extra line to the Coke Oven quest :)

**Pull request merged**
