### PR TITLE
[Expert] More Recipe Overhauls

### PR DESCRIPTION
**Pull request by MuteTiefling**
Extra recipe for Plastic:
image

Speed up basic plastic by batching it
image

Mekanism machine updates
Painting Machine
image

Pigment Extractor
image

Pigment Mixer
image

Mek upgrades
Stone Generator
image

Laser Dissipation
image

Shearing
image

Geiger
image

Elytra
image

Frost Walker
image

Geothermal
image

### CODE REVIEW

**Comment by MuteTiefling** [comment]
Meka Tool
image
Moving up as default recipes leave it way too late to be useful

Travel Staff
image

Teleportation Unit
image

Vein Mining
image

Silk Touch
image

Attack Amplification
image

Farming Unit
image

Excavation
image

**Comment by MuteTiefling** [comment]
Modification Station brought forward since meka tool and suit are both earlier
image

Security Desk too
image

**Review by NillerMedDild — APPROVED** [review]
Looks good!

I see you removed the Coal Petcoke Steel recipe to fix a bug, but is that really needed? Would be nice to be able to use both Coal types

**Comment by NillerMedDild** [comment]
.... please ignore my comment, I missed the actual change you made. I blame my mobile :P

**Comment by NillerMedDild** [comment]
.... please ignore my comment, I missed the actual change you made. I blame my mobile :P

**Comment by MuteTiefling** [comment]
reading this on mobile is pain :D

**Pull request merged**
