### PR TITLE
Add Irradiated Occultism Miner for fissile fuel production

### PR DESCRIPTION
**Pull request by theboo**
Adds occultism mineshaft miner for fissile fuel materials.

Also boosted the rolls per operation of the current djinni ore miner.

### CODE REVIEW

**Comment by theboo** [comment]
just noticed the config seems to override the recipe for the ore miner output, forgot the config existed tbh... Can switch to that unless we plan on bumping that miner up to marid tier. I'll fix that in either direction tomorrow

**Review by MuteTiefling — APPROVED** [review]
Looks good. Just needs that rate increase we discussed.

**Comment by theboo** [comment]
should be good to go now, I think? also added damage:0 with weakNBT to the iesnium pick in the irradiated recipe as i saw it being used elsewhere while scrolling through

**Comment by MuteTiefling** [comment]
Yeah, good catch with the pick.^_^

**Pull request merged**
