### PR TITLE
Sort client bee larva item registry alphabetically

### PR DESCRIPTION
**Pull request by Quezler**
For #4944 i had to gather the colors of all bees, naturally i didn't want to do that by hand, so i wrote a script.

The original ones (that were messy because i kept the sort order intact to make reviewing that pr easier) are attached:
[1_color.php.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/8897972/1_color.php.txt)
[2_color.php.txt](https://github.com/EnigmaticaModpacks/Enigmatica6/files/8897973/2_color.php.txt)

The automation file in this pull request instead sorts by directory name, and then the name of the bee. (manual exempt)

Unlike the ci scripts this file will probably rarely see some use, but it feels worthwhile to include nonetheless. ^-^

```
$ php automation/php/resourcefulbees-colors.php
// alloy
{name: 'brass',          band: 0x998d38, outline: 0x998d38},
{name: 'bronze',         band: 0xd38c53, outline: 0xd38c53},
{name: 'constantan',     band: 0xd8876b, outline: 0xd8876b},
{name: 'electrum',       band: 0xe5b840, outline: 0xe5b840},
{name: 'enderium',       band: 0x0a4a4a, outline: 0x0a4a4a},
{name: 'invar',          band: 0xdfe5e2, outline: 0xdfe5e2},
{name: 'lumium',         band: 0xe5f3b5, outline: 0xe5f3b5},
{name: 'signalum',       band: 0xfd641a, outline: 0xfd641a},
{name: 'steel',          band: 0x858585, outline: 0x858585},
// dev
{name: 'kitten',         band: 0xeaa939, outline: 0x4c483b},
{name: 'oreo',           band: 0x442920, outline: 0xe1d9b8},
{name: 'starry_lexxie',  band: 0xffffff, outline: 0xffa500},
{name: 'yeti',           band: 0xe9f4f6, outline: 0x777e86},
// gem
{name: 'diamond',        band: 0x00ffff, outline: 0x00ffff},
{name: 'emerald',        band: 0x18eb09, outline: 0x18eb09},
{name: 'lapis',          band: 0x345ec3, outline: 0x345ec3},
{name: 'redstone',       band: 0xaa0f01, outline: 0xaa0f01},
// magic
{name: 'bloody',         band: 0x80251f, outline: 0x80251f},
{name: 'carbee',         band: 0xe39c27, outline: 0xe39c27},
{name: 'elven',          band: 0xff66cc, outline: 0xff66cc},
{name: 'infused',        band: 0x1bb373, outline: 0x1bb373},
{name: 'mana',           band: 0x4c97ff, outline: 0x4c97ff},
{name: 'otherworldly',   band: 0x1d1d24, outline: 0x1d1d24},
{name: 'sky',            band: 0x73d0ff, outline: 0x73d0ff},
{name: 'starry',         band: 0x002184, outline: 0x002184},
{name: 'tainted',        band: 0xcc6d3d, outline: 0xcc6d3d},
{name: 'terrestrial',    band: 0x5bf23d, outline: 0x5bf23d},
// material
{name: 'clay',           band: 0xacaebd, outline: 0xacaebd},
{name: 'enderslime',     band: 0xa777e1, outline: 0xa777e1},
{name: 'gravel',         band: 0x968e8e, outline: 0x968e8e},
{name: 'ichor',          band: 0xf7731f, outline: 0xf7731f},
{name: 'shepherd',       band: 0x945c45, outline: 0x945c45},
{name: 'skyslime',       band: 0x4ab1a4, outline: 0x4ab1a4},
// metal
{name: 'aluminum',       band: 0xdce6f7, outline: 0xdce6f7},
{name: 'cobalt',         band: 0x20adc9, outline: 0x20adc9},
{name: 'copper',         band: 0xbb5b30, outline: 0xbb5b30},
{name: 'frosty',         band: 0xb9d3ec, outline: 0xb9d3ec},
{name: 'gold',           band: 0xffdc00, outline: 0xffdc00},
{name: 'iron',           band: 0xffcc99, outline: 0xffcc99},
{name: 'lead',           band: 0x333952, outline: 0x333952},
{name: 'nickel',         band: 0x8c8f86, outline: 0x8c8f86},
{name: 'osmium',         band: 0xc1e0e7, outline: 0xc1e0e7},
{name: 'regal',          band: 0xebbe76, outline: 0xebbe76},
{name: 'silver',         band: 0xc5d1fe, outline: 0xc5d1fe},
{name: 'tin',            band: 0x7d81a4, outline: 0x7d81a4},
{name: 'uranium',        band: 0x333c2f, outline: 0x333c2f},
{name: 'zinc',           band: 0x818653, outline: 0x818653},
// natural
{name: 'brutish_zombee', band: 0x2f4e32, outline: 0x2f4e32},
{name: 'clogged',        band: 0xba9d7b, outline: 0xba9d7b},
{name: 'coal',           band: 0x303030, outline: 0x303030},
{name: 'creeper',        band: 0x0c9f0a, outline: 0x0c9f0a},
{name: 'ender',          band: 0x339786, outline: 0x339786},
{name: 'forest',         band: 0x4c4c26, outline: 0x4c4c26},
{name: 'glowstone',      band: 0xffbc5e, outline: 0xffbc5e},
{name: 'icy',            band: 0x92b9fe, outline: 0x92b9fe},
{name: 'obsidian',       band: 0x663399, outline: 0x663399},
{name: 'pigman',         band: 0x885956, outline: 0x885956},
{name: 'rgbee',          band: 0xffffff, outline: 0xffffff},
{name: 'rocky',          band: 0x8f8f8f, outline: 0x8f8f8f},
{name: 'sand',           band: 0xe7e4bb, outline: 0xe7e4bb},
{name: 'skeleton',       band: 0xf6f2e6, outline: 0xf6f2e6},
{name: 'slimy',          band: 0x73c262, outline: 0x73c262},
{name: 'water',          band: 0x5979ef, outline: 0x5979ef},
{name: 'zombie',         band: 0x2f4e32, outline: 0x2f4e32},
// nether
{name: 'blaze',          band: 0xfff32d, outline: 0xfff32d},
{name: 'ghast',          band: 0xfaebd7, outline: 0xfaebd7},
{name: 'netherite',      band: 0x654740, outline: 0x654740},
{name: 'wither',         band: 0x444444, outline: 0x444444},
{name: 'nether_quartz',  band: 0xd4caba, outline: 0xd4caba},
// special
{name: 'boobee',         band: 0xe9f3ea, outline: 0xe9f3ea},
{name: 'clockwork',      band: 0x70522e, outline: 0x70522e},
{name: 'direbee20',      band: 0x859292, outline: 0x859292},
{name: 'dusty_mummbee',  band: 0xe7e4bb, outline: 0xe7e4bb},
{name: 'generikbee',     band: 0xf25843, outline: 0xf25843},
{name: 'soup',           band: 0x8b7173, outline: 0x8b7173},
{name: 'spelling',       band: 0x905e43, outline: 0x905e43},
{name: 'wasabee',        band: 0x59a523, outline: 0x59a523},
// tech
{name: 'basalz',         band: 0x1b141d, outline: 0x1b141d},
{name: 'blitz',          band: 0xdef7fa, outline: 0xdef7fa},
{name: 'blizz',          band: 0x37b7fe, outline: 0x37b7fe},
{name: 'industrious',    band: 0xce7dce, outline: 0xce7dce},
{name: 'pcbee',          band: 0x7a7f80, outline: 0x7a7f80},
// manual
{name: 'abbee',          band: 0xe5ded5, outline: 0xffb1c5},
```

65 insertions & 56 deletions in item_registry.js explained:
- 11 of them are new `// directory` comments
- 1 whiteline above the special bees got removed (after being introduced by #4995 to reference `combVariants` diff)
- 1 entry got removed, since this script no longer can generate the catnip larva from #4996 (present in the above txts)

### CODE REVIEW

**Review by NielsPilgaard — CHANGES_REQUESTED** [review]
I'd rather not merge the php automation, as I doubt it would be used much, but I'll gladly take the cleanup / ordering 😄

**Comment by Quezler** [comment]
Hmm, unfortunate, always nice to keep the generators around from which computed data is derived, but oh well 🙃

**Review by NielsPilgaard — APPROVED** [review]

**Comment by NielsPilgaard** [comment]
> Hmm, unfortunate, always nice to keep the generators around from which computed data is derived, but oh well 🙃

Yes, if people know how to use them :P I for one, do not.

**Comment by Quezler** [comment]
it's just `php ./automation/php/resourcefulbees-colors` and you get the output quoted above ^-^ (after running composer once, just like node needs npm install)

**Pull request merged**
