### PR TITLE
Automation quests and other minor quest fixes

### PR DESCRIPTION
**Pull request by Rodg88**
WIP, but the chapter is hidden. Pretty Pipes quests are in the chapter now so might be confusing if it gets released as is, as the storage chapter references them but they won't be accessible.

### CODE REVIEW

**Comment by Rodg88** [comment]
Should be ready now!
image

**Comment by Rodg88** [comment]
Also some additions in Storage 
image

And one more in Tinker's for the filtered ducts.

**Comment by Rodg88** [comment]
Also included fixes to the IF quests (they had some weird dependencies), and one or two spelling errors.

**Comment by MuteTiefling** [comment]
Cool thanks!

**Pull request merged**
