### PR TITLE
Update Apotheosis configs to new JSON format

### PR DESCRIPTION
**Pull request by MuteTiefling**
Puts our old caps back in place for the new version, but also updates the items used for various upgrades:

Normal Mode:
image
image
image
image

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
I might suggest you add new "higher tier" modifiers that have extended caps (specifically for the delay modifiers)
You could also add "super" modifiers that provide buffs to multiple stats at once, which might be neat™

**Comment by MuteTiefling** [comment]
Expert Recipes: 
image
image
image
image
image
image
image

**Comment by MuteTiefling** [comment]
Limit Boon of the Earth (drops ores when breaking stone) to Level 3 and overworld or chunks.

**Review by NillerMedDild — APPROVED** [review]
Very nice 👌 
If I hadn't looked at the json I wouldn't know to dual wield the required items, any chance you could have a look at making JEI more explicit here @Shadows-of-Fire? :)

**Comment by theboo** [comment]
there is a book now!! i believe it explains this in detail!

**Comment by MuteTiefling** [comment]
It actually shows it quite nicely in JEI, just not in the pictures above:

image

image

image
image


The limits are also displayed there
image

**Comment by Shadows-of-Fire** [comment]
Yep, it's all explained as well as it can be between both the book and JEI.

**Comment by NielsPilgaard** [comment]
Oh lovely, my bad 👍

**Comment by Shadows-of-Fire** [comment]
I want to note (before moto forgets) that this omits the Silent modifier, added in 4.8.99B, so that'll have to be added to the expert changes (for consistency).

**Comment by MuteTiefling** [comment]
Thanks for the reminder :D Easier to keep track of things here

**Pull request merged**
