### PR TITLE
added quark cactus paste as a source of green dye

### PR DESCRIPTION
**Pull request by Rodg88**

### CODE REVIEW

**Review by MuteTiefling — COMMENTED** [review]
Is cactus paste obtainable ? I couldn't sworn there was no way to craft it currently.

**Comment by Rodg88** [comment]
i crushed cactus and got it

**Comment by NillerMedDild** [comment]
I don't really see the need to add it as a dye source, what do we gain from it here?

**Comment by Rodg88** [comment]
making it work with rgbee combs for making more green dye mainly

**Comment by NillerMedDild** [comment]
Err.. sure :P

**Pull request merged**
